### ISSUE TITLE
Ajax?

### ISSUE THREAD

**Issue by Dakuan** [node-js-libs/node.io#101]
Any clues for dealing with pages that have content loaded in via AJAX?

**Comment by chriso** [comment]
Set the `jsdom` and `external_resources` options to true to use JSDOM with jQuery instead of the default parser. The jQuery `$` object is available as a `getHtml` argument. You also have access to a `this.window` object. You could use a `window.onload`, `$(function () { /* ready */ })` or just a `setTimeout` to wait for the content to be loaded.

**Comment by jonlong** [comment]
I'm currently testing `$.ready(function(){});` inside of the `run` method and getting an `Object ..... has no method 'ready` in the process.  Is this related or am I simply configuring/calling something incorrectly?

Thanks!

**Comment by chriso** [comment]
Sorry, `$.ready` won't work. Use the short form jquery ready:

``` javascript
$(function () {
    //doc is ready
});
```

**Comment by jonlong** [comment]
Excellent, thank you!
