### ISSUE TITLE
able to stop timeout exiting the process?

### ISSUE THREAD

**Issue by parkotron** [node-js-libs/node.io#20]
I've just started implementing a build tool that needs to scrape some data and return as a jsonp request. The problem I have is that the node.io timeout kills the parent process which I want to keep live all the time, is it possible to exit or tidy the node.io scrape process without killing the entire node process?

**Comment by chriso** [comment]
So you're calling node.io from within your app? If so, you need to specify a callback to `start()` otherwise the default callback is used (which exits the process). Try:

```
var nodeio = require('node.io'), 
    options = {timeout: 10},
    job = require('my_job');

nodeio.start(job, options, function (err, output) {
    //Handle the error or output here..
}, true);
```

See [this block of code](https://github.com/chriso/node.io/blob/master/lib/node.io/processor.js#L41-L53) for more info on the `start()` method.

**Comment by jscheel** [comment]
I'm having some trouble with this. I have a job here: http://pastie.org/1656182

I want to run it with my own error handling, so I do it like so: http://pastie.org/1656186

But, I get Object has no method 'getHTML' on my job when I run it. Any thoughts?

**Comment by chriso** [comment]
This isn't so obvious from the documentation, but the first line should be: `var job = require('./scrapeJob').job;` 

In node, requiring a module loads the `exports` object, so if your job is defined as `exports.job` then you need to say `require('job').job`.

In an update I'm going to make it so that you can just define jobs using `this` (while still being backwards compatible):

```
this = require('node.io').job({
  options: {timeout: 10}
  input: false,
  run: function() {
    var self = this;
    this.getHTML(this.options.args[0], function(err, $){
      var body = $('#mainBody').innerHTML;
      self.emit(body);
    });
  }
})
```

**Comment by chriso** [comment]
Just realised that I gave you the wrong advice in the previous post, sorry.
