### ISSUE TITLE
Pause, wait, etc

### ISSUE THREAD

**Issue by PmegaOcalc** [node-js-libs/node.io#25]
Is there a possibility to make a delay between jobs/threads when input is true?
Meaning, that after scraping, reducing, outputting, etc the data node.io will wait before scraping again.

**Comment by chriso** [comment]
Hey, you can use the undocumented `wait` option - the code is [here](https://github.com/chriso/node.io/blob/master/lib/node.io/process_worker.js#L149-153) - it just adds a delay (in seconds) between emitting and the thread ending.

What's your use case? It's probably easiest to just implement the delay yourself.. Instead of calling `this.emit()` or skip/retry/etc, just call `setTimeout(this.emit, seconds * 1000)`

**Comment by PmegaOcalc** [comment]
I'm crawling an RSS feed continuously and would like to use proper crawling etiquette.
Thank you, your implementation works just great.
