### ISSUE TITLE
Early exit?

### ISSUE THREAD

**Issue by leei** [node-js-libs/node.io#4]
I'm using node.io to run a bit of a web scraper (grabbing game data from nhl.com) and I have a problem wherein node.io exits before all of the getHtml requests are completed. How does it decide when to exit?  This uses node 0.2.5.

**Comment by chriso** [comment]
node.io exits when either all of the input is consumed, or in the case of `input: false`, after one cycle of `run()`. Being asynchronous, node.io has a few ways of determining if `run()` was completed successfully, namely that either `emit()`, `fail()`, or `skip()` was called - i.e. these can only be called once per `run()` - any subsequent calls are ignored.

If you're scraping multiple pages (I assume from multiple getHtml requests), the correct way would be to have each URL as an element of input, or maybe have keywords as elements of input which you later build the URL from).

[This example highlights the incorrect and correct way to make multiple requests](https://gist.github.com/749067)

This is all assuming that node.io exits with `OK: Job Complete`. If not, it may be a bug. If you run node.io with the `-g` switch it will log each request that it makes - this may help you figure out what's going on.

If you want to send me the code privately (cohara87@gmail.com), I'd be happy to fix it for you.

-Chris

**Comment by chriso** [comment]
Scraping examples are a bit scarce at the moment. I'm in the process of building the wiki https://github.com/chriso/node.io/wiki which will have more in depth tutorials and examples soon.

**Comment by leei** [comment]
Got it.  Only one of emit, fail, or skip per run...

That was the key.  And since I was emitting multiple times per job, it must have been counting these and then exited as soon as it had enough, which was of course before it had processed all the pages...

Maybe there's some way to warn the user when emit is submitted more than once per job...  Run emit() and then redefine it per job?

**Comment by chriso** [comment]
Make sure you're using the newest version of node.io - I recently fixed a bug where subsequent emit()'s were decrementing the internal counter. The latest version ignores these calls now. 

The reason I don't issue a warning on calling emit, skip, fail after the thread is complete is because there are times when multiple calls are unavoidable. For example, a thread might timeout (and automatically call fail) from a setTimeout call outside of the main stack. I may issue a warning down the track when using the `-g` debug switch however.
