### ISSUE TITLE
Generate POST request from Form

### ISSUE THREAD

**Issue by ma2rten** [node-js-libs/node.io#41]
When screen scraping, it can be very convenient sometimes, to automatically generate a post request from a form in the html document. To get the point across, here is some code I wrote which does that for me. 

```
    submitForm = ($, callback) =>
        body = {}

        for item in $('form select, form input[type!=submit], form input[type=submit]:first')
            if $(item).val()
                body[$(item).attr('name')] = $(item).val()

        url = root + $('form').attr('action').replace('&amp;', '&')
        header = {'Content-Type': 'application/x-www-form-urlencoded'}

        @postHtml url, body, header, callback
```

Would it be possible to have that feature in node.io?

**Comment by chriso** [comment]
This is interesting and definitely useful. I'll have to think of a way of implementing it so it plays nice with the default selector engine ([soupselect](https://github.com/harryf/node-soupselect)) - I don't think it can currently handle `$('form select, form input[type!=submit], form input[type=submit]:first')`

**Comment by zdwalter** [comment]
any update?

**Comment by chriso** [comment]
@zdwalter this would be handy feature but it's not something I have time to implement right now. If someone wants to have a stab at it I'll gladly accept a pull request, otherwise it's fairly low priority.

**Comment by krzysztofantczak** [comment]
I see that this comment exist since 2 years, but i'm not able to resist with answering on that... The thing is, that crawler without basic stuff as POST support when You thinking about real life crawlers are mandatory these days. Ok, if You have only fun with it, and You are scrapping some google results You're ok, but it can't work with some more advanced websites, where even internal navigation is based on POST requests. Is this project alive? Can we bring it to live if it's not? I can see some nice ideas here, but codebase seems to be outdated, and there is lack of really MUST HAVE features for any good crawler framework.
