### ISSUE TITLE
Request Tests Fail

### ISSUE THREAD

**Issue by felixhummel** [node-js-libs/node.io#54]
In `test/request.test.js` I get twelve `ECONNREFUSED` errors (on lines lines 66, 92, ...).

Is this a known problem? Could be an expresso issue. Which versions are _you_ using assuming it works for you?

`$ git rev-parse HEAD
89d775fb3e263fa67b23d7fbf64fd2ad19186c45
$ node --version
v0.4.11
$ expresso --version
0.8.1`

Cheers!
  Felix

**Comment by chriso** [comment]
I assume it's some sort of permission error, as the tests need to create a few test http servers on various ports so that the scraping methods can be tested.

I have had this issue in the past (see my original workaround [here](https://github.com/chriso/node.io/blob/master/test/request.test.js#L10-15)), although I don't seem to have it anymore.

I'm using:

``` bash
$ node -v && expresso -v
v0.4.11
0.8.1
```

**Comment by chriso** [comment]
Is this still an issue? Works for me in 0.6+
