### ISSUE TITLE
job completes twice

### ISSUE THREAD

**Issue by discoverpost** [node-js-libs/node.io#89]
https://gist.github.com/2260017

nodeio.start(myjob, function (err) {
    //console.log(output); //[4,5,6]
}, false);

why do jobs that use this function complete twice? gives me an empty object initially

**Comment by chriso** [comment]
There's a few issues with the script. Firstly, you've got your main code in the `input` method rather than the `run` method. Secondly, you're calling `callback` twice, once at the end of the input and another when the asynchronous `getHtml` returns. Remember to only ever emit from the most nested callback.

This is the fixed version of your code

``` javascript
var nodeio = require('node.io');
var reddit = "http://www.reddit.com/";
var options = {
    timeout: 100,
    max: 2,
    retry: 5
};

var myjob = new nodeio.Job(options, {
    input: false,
    run: function () {
        var self = this;
        this.getHtml(reddit, function (err, $) {
            if (err) self.exit(err);
            var titles = [];
            $('a.title').each(function (title) {
                titles.push(title.text);
            });
            this.emit(titles);
        });
    }
});

nodeio.start(myjob, function (err, titles) {
    console.log(titles);
}, true);
```
