### ISSUE TITLE
cheerio

### ISSUE THREAD

**Issue by lookfirst** [node-js-libs/node.io#95]
Seems to be a nice replacement for jsdom? https://github.com/MatthewMueller/cheerio

**Comment by chriso** [comment]
FYI jsdom isn't the default parser in node.io, it uses the same [parser](https://github.com/tautologistics/node-htmlparser) and [selector engine](https://github.com/harryf/node-soupselect) as `cheerio`. The [layer on top](https://github.com/chriso/node.io/wiki/API---CSS-Selectors-and-Traversal-methods) in node.io is a collection of custom traversal methods built before `cheerio` was created. 

The next version of node.io will include a better collection of functionality - similar to `cheerio` but with more focus on scraping rather than trying to be a drop-in replacement for jQuery.

**Comment by lookfirst** [comment]
Right, I'm not questioning the parser, I'm questioning the available selector methods, of which cheerio is superior. ;-)

I figured out a workaround... @get .... (err,data) => ... $ = cheerio.load(data)
