### ISSUE TITLE
setMaxListeners()

### ISSUE THREAD

**Issue by jamesduncombe** [node-js-libs/node.io#96]
Hi guys,

Just wondering whether anyone else has bumped into this:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

I know why it's doing it as I'm hitting over 11 pages at once so I guess it's tripping it.

Is there a way to get round this?

Cheers,

James

**Comment by chriso** [comment]
It's a [ridiculous default](https://github.com/joyent/node/blob/master/lib/events.js#L35-45) [buried](https://github.com/joyent/node/blob/master/lib/events.js#L163-167) in the node.js source.

EventEmitters have a `setMaxListeners` method allowing you to raise this number but the problem is that you often won't have access to EventEmitters buried in a dependency.

I've [submitted a patch](https://github.com/joyent/node/pull/3014) to make the max globally configurable but it was shutdown because the EventEmitter api is "closed".

The only solution I can think of is terrible and shouldn't be used - patching a method from the EventEmitter prototype that you know will be called

``` javascript
var EventEmitter = require('events').EventEmitter
  , on = EventEmitter.prototype.on;
EventEmitter.prototype.on = function () {
    this._maxListeners = Infinity;
    on.apply(this, arguments);
};
```

**Comment by chriso** [comment]
Say something in the [node.js ticket](https://github.com/joyent/node/issues/3215) if you can. The more people that complain, the more likely they'll change it.

**Comment by jamesduncombe** [comment]
Hi Chris,

Thanks for the quick reply. I checked out the node.js manual before posting but then hit a wall when I figured (as you said) that it's on a dependency so I can't use setMaxListeners().

I'll put something in the node.js ticket.

Thanks for the solution too. I know it's not pretty but I might need to use it.

Cheers,

James
