### ISSUE TITLE
Terminating job with high memory usage

### ISSUE THREAD

**Issue by phillro** [node-js-libs/node.io#97]
Occasionally a job makes a request to a very large file, this leads to:

"FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory"

The timeout option does not seem to be failing while the request is still be written to. Anyway to fail this based on memory usage?

**Comment by chriso** [comment]
I'd suggest using a separate request library with stream support for this sort of task to prevent buffering the entire file in memory, e.g. [mikeal/request](https://github.com/mikeal/request). You can still use most of the functionality of node.io, just use this instead of the inbuilt `this.get()`.

``` javascript
var request = require('request');
request('http://example.com/image.png').pipe(fs.createWriteStream('image.png'))
```

You could also look into raising the memory limit of V8. I think this is around the 1GB mark but is now configurable with a command line option.
